# Generated by Django 4.2.28 on 2026-02-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_core_hub", "0002_celestial_cache"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dscanitem",
            new_name="aa_core_hub_type_na_72d917_idx",
            old_name="aa_core_hu_type_n_idx",
        ),
        migrations.RenameIndex(
            model_name="solarsystemcelestial",
            new_name="aa_core_hub_solar_s_f4dfa4_idx",
            old_name="aa_core_cel_sys_type_idx",
        ),
        migrations.RenameIndex(
            model_name="structure",
            new_name="aa_core_hub_solar_s_df3cfd_idx",
            old_name="aa_core_hu_solar_s_idx",
        ),
        migrations.RenameIndex(
            model_name="structure",
            new_name="aa_core_hub_owner_a_cd18d5_idx",
            old_name="aa_core_hu_owner_a_idx",
        ),
        migrations.RenameIndex(
            model_name="structure",
            new_name="aa_core_hub_owner_c_4ff917_idx",
            old_name="aa_core_hu_owner_c_idx",
        ),
        migrations.RenameIndex(
            model_name="structure",
            new_name="aa_core_hub_type_id_5e2ca9_idx",
            old_name="aa_core_hu_type_i_idx",
        ),
        migrations.RenameIndex(
            model_name="structuretimer",
            new_name="aa_core_hub_occurs__ddd481_idx",
            old_name="aa_core_hu_occurs_idx",
        ),
        migrations.RenameIndex(
            model_name="structuretimer",
            new_name="aa_core_hub_priorit_85b3d1_idx",
            old_name="aa_core_hu_priorit_idx",
        ),
        migrations.AlterUniqueTogether(
            name="solarsystemcelestial",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="solarsystemcelestial",
            name="celestial_id",
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="solarsystemcelestial",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
